version: '3.8'

services:
  ee-agent:
    build: .
    container_name: ee-research-scout
    ports:
      - "8000:8000"
    environment:
      - LLM_PROVIDER=${LLM_PROVIDER}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ANTHROPIC_MODEL=${ANTHROPIC_MODEL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_MODEL=${OPENROUTER_MODEL}
      - IEEE_API_KEY=${IEEE_API_KEY}
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    volumes:
      - ./:/app
    depends_on:
      - neo4j
    restart: unless-stopped
    networks:
      - ee-network

  neo4j:
    image: neo4j:latest
    container_name: ee-knowledge-graph
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_dbms_memory_heap_max__size=2G
    volumes:
      - neo4j_data:/data
    restart: unless-stopped
    networks:
      - ee-network

networks:
  ee-network:
    driver: bridge

volumes:
  neo4j_data: